/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeltaRouteImport } from './routes/delta'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpillStudentIdRouteImport } from './routes/spill.$studentId'
import { Route as LiveoktSessionIdRouteImport } from './routes/liveokt.$sessionId'
import { Route as AuthedPrivateRouteImport } from './routes/_authed/private'
import { Route as LiveoktSessionIdIndexRouteImport } from './routes/liveokt.$sessionId.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as LiveoktSessionIdStegStepRouteImport } from './routes/liveokt.$sessionId.steg.$step'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeltaRoute = DeltaRouteImport.update({
  id: '/delta',
  path: '/delta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpillStudentIdRoute = SpillStudentIdRouteImport.update({
  id: '/spill/$studentId',
  path: '/spill/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveoktSessionIdRoute = LiveoktSessionIdRouteImport.update({
  id: '/liveokt/$sessionId',
  path: '/liveokt/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPrivateRoute = AuthedPrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => AuthedRoute,
} as any)
const LiveoktSessionIdIndexRoute = LiveoktSessionIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LiveoktSessionIdRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveoktSessionIdStegStepRoute =
  LiveoktSessionIdStegStepRouteImport.update({
    id: '/steg/$step',
    path: '/steg/$step',
    getParentRoute: () => LiveoktSessionIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/delta': typeof DeltaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/private': typeof AuthedPrivateRoute
  '/liveokt/$sessionId': typeof LiveoktSessionIdRouteWithChildren
  '/spill/$studentId': typeof SpillStudentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/liveokt/$sessionId/': typeof LiveoktSessionIdIndexRoute
  '/liveokt/$sessionId/steg/$step': typeof LiveoktSessionIdStegStepRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/delta': typeof DeltaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/private': typeof AuthedPrivateRoute
  '/spill/$studentId': typeof SpillStudentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/liveokt/$sessionId': typeof LiveoktSessionIdIndexRoute
  '/liveokt/$sessionId/steg/$step': typeof LiveoktSessionIdStegStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/delta': typeof DeltaRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/_authed/private': typeof AuthedPrivateRoute
  '/liveokt/$sessionId': typeof LiveoktSessionIdRouteWithChildren
  '/spill/$studentId': typeof SpillStudentIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/liveokt/$sessionId/': typeof LiveoktSessionIdIndexRoute
  '/liveokt/$sessionId/steg/$step': typeof LiveoktSessionIdStegStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/delta'
    | '/login'
    | '/logout'
    | '/private'
    | '/liveokt/$sessionId'
    | '/spill/$studentId'
    | '/api/auth/$'
    | '/liveokt/$sessionId/'
    | '/liveokt/$sessionId/steg/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/delta'
    | '/login'
    | '/logout'
    | '/private'
    | '/spill/$studentId'
    | '/api/auth/$'
    | '/liveokt/$sessionId'
    | '/liveokt/$sessionId/steg/$step'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/delta'
    | '/login'
    | '/logout'
    | '/_authed/private'
    | '/liveokt/$sessionId'
    | '/spill/$studentId'
    | '/api/auth/$'
    | '/liveokt/$sessionId/'
    | '/liveokt/$sessionId/steg/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  DeltaRoute: typeof DeltaRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  LiveoktSessionIdRoute: typeof LiveoktSessionIdRouteWithChildren
  SpillStudentIdRoute: typeof SpillStudentIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delta': {
      id: '/delta'
      path: '/delta'
      fullPath: '/delta'
      preLoaderRoute: typeof DeltaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spill/$studentId': {
      id: '/spill/$studentId'
      path: '/spill/$studentId'
      fullPath: '/spill/$studentId'
      preLoaderRoute: typeof SpillStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liveokt/$sessionId': {
      id: '/liveokt/$sessionId'
      path: '/liveokt/$sessionId'
      fullPath: '/liveokt/$sessionId'
      preLoaderRoute: typeof LiveoktSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/private': {
      id: '/_authed/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof AuthedPrivateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/liveokt/$sessionId/': {
      id: '/liveokt/$sessionId/'
      path: '/'
      fullPath: '/liveokt/$sessionId/'
      preLoaderRoute: typeof LiveoktSessionIdIndexRouteImport
      parentRoute: typeof LiveoktSessionIdRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liveokt/$sessionId/steg/$step': {
      id: '/liveokt/$sessionId/steg/$step'
      path: '/steg/$step'
      fullPath: '/liveokt/$sessionId/steg/$step'
      preLoaderRoute: typeof LiveoktSessionIdStegStepRouteImport
      parentRoute: typeof LiveoktSessionIdRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedPrivateRoute: typeof AuthedPrivateRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPrivateRoute: AuthedPrivateRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface LiveoktSessionIdRouteChildren {
  LiveoktSessionIdIndexRoute: typeof LiveoktSessionIdIndexRoute
  LiveoktSessionIdStegStepRoute: typeof LiveoktSessionIdStegStepRoute
}

const LiveoktSessionIdRouteChildren: LiveoktSessionIdRouteChildren = {
  LiveoktSessionIdIndexRoute: LiveoktSessionIdIndexRoute,
  LiveoktSessionIdStegStepRoute: LiveoktSessionIdStegStepRoute,
}

const LiveoktSessionIdRouteWithChildren =
  LiveoktSessionIdRoute._addFileChildren(LiveoktSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  DeltaRoute: DeltaRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  LiveoktSessionIdRoute: LiveoktSessionIdRouteWithChildren,
  SpillStudentIdRoute: SpillStudentIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
