/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as LiveoktIdRouteImport } from './routes/liveokt.$id'
import { Route as DashboardVelgPastanderRouteImport } from './routes/_dashboard/velg-pastander'
import { Route as DashboardMinSamlingRouteImport } from './routes/_dashboard/min-samling'
import { Route as DashboardLagreFagpratRouteImport } from './routes/_dashboard/lagre-fagprat'
import { Route as DashboardLagFagpratRouteImport } from './routes/_dashboard/lag-fagprat'
import { Route as AuthedPrivateRouteImport } from './routes/_authed/private'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardFagpratIdRouteImport } from './routes/_dashboard/fagprat.$id'
import { Route as LiveoktIdStegStepRouteImport } from './routes/liveokt.$id.steg.$step'
import { Route as DashboardFagpratIdRedigerRouteImport } from './routes/_dashboard/fagprat.$id.rediger'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const LiveoktIdRoute = LiveoktIdRouteImport.update({
  id: '/liveokt/$id',
  path: '/liveokt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVelgPastanderRoute = DashboardVelgPastanderRouteImport.update({
  id: '/velg-pastander',
  path: '/velg-pastander',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMinSamlingRoute = DashboardMinSamlingRouteImport.update({
  id: '/min-samling',
  path: '/min-samling',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLagreFagpratRoute = DashboardLagreFagpratRouteImport.update({
  id: '/lagre-fagprat',
  path: '/lagre-fagprat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLagFagpratRoute = DashboardLagFagpratRouteImport.update({
  id: '/lag-fagprat',
  path: '/lag-fagprat',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthedPrivateRoute = AuthedPrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardFagpratIdRoute = DashboardFagpratIdRouteImport.update({
  id: '/fagprat/$id',
  path: '/fagprat/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const LiveoktIdStegStepRoute = LiveoktIdStegStepRouteImport.update({
  id: '/steg/$step',
  path: '/steg/$step',
  getParentRoute: () => LiveoktIdRoute,
} as any)
const DashboardFagpratIdRedigerRoute =
  DashboardFagpratIdRedigerRouteImport.update({
    id: '/rediger',
    path: '/rediger',
    getParentRoute: () => DashboardFagpratIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/private': typeof AuthedPrivateRoute
  '/lag-fagprat': typeof DashboardLagFagpratRoute
  '/lagre-fagprat': typeof DashboardLagreFagpratRoute
  '/min-samling': typeof DashboardMinSamlingRoute
  '/velg-pastander': typeof DashboardVelgPastanderRoute
  '/liveokt/$id': typeof LiveoktIdRouteWithChildren
  '/fagprat/$id': typeof DashboardFagpratIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/fagprat/$id/rediger': typeof DashboardFagpratIdRedigerRoute
  '/liveokt/$id/steg/$step': typeof LiveoktIdStegStepRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/private': typeof AuthedPrivateRoute
  '/lag-fagprat': typeof DashboardLagFagpratRoute
  '/lagre-fagprat': typeof DashboardLagreFagpratRoute
  '/min-samling': typeof DashboardMinSamlingRoute
  '/velg-pastander': typeof DashboardVelgPastanderRoute
  '/liveokt/$id': typeof LiveoktIdRouteWithChildren
  '/fagprat/$id': typeof DashboardFagpratIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/fagprat/$id/rediger': typeof DashboardFagpratIdRedigerRoute
  '/liveokt/$id/steg/$step': typeof LiveoktIdStegStepRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/_authed/private': typeof AuthedPrivateRoute
  '/_dashboard/lag-fagprat': typeof DashboardLagFagpratRoute
  '/_dashboard/lagre-fagprat': typeof DashboardLagreFagpratRoute
  '/_dashboard/min-samling': typeof DashboardMinSamlingRoute
  '/_dashboard/velg-pastander': typeof DashboardVelgPastanderRoute
  '/liveokt/$id': typeof LiveoktIdRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/fagprat/$id': typeof DashboardFagpratIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/fagprat/$id/rediger': typeof DashboardFagpratIdRedigerRoute
  '/liveokt/$id/steg/$step': typeof LiveoktIdStegStepRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/register'
    | '/private'
    | '/lag-fagprat'
    | '/lagre-fagprat'
    | '/min-samling'
    | '/velg-pastander'
    | '/liveokt/$id'
    | '/fagprat/$id'
    | '/api/auth/$'
    | '/fagprat/$id/rediger'
    | '/liveokt/$id/steg/$step'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/register'
    | '/private'
    | '/lag-fagprat'
    | '/lagre-fagprat'
    | '/min-samling'
    | '/velg-pastander'
    | '/liveokt/$id'
    | '/fagprat/$id'
    | '/api/auth/$'
    | '/fagprat/$id/rediger'
    | '/liveokt/$id/steg/$step'
  id:
    | '__root__'
    | '/_authed'
    | '/_dashboard'
    | '/login'
    | '/logout'
    | '/register'
    | '/_authed/private'
    | '/_dashboard/lag-fagprat'
    | '/_dashboard/lagre-fagprat'
    | '/_dashboard/min-samling'
    | '/_dashboard/velg-pastander'
    | '/liveokt/$id'
    | '/_dashboard/'
    | '/_dashboard/fagprat/$id'
    | '/api/auth/$'
    | '/_dashboard/fagprat/$id/rediger'
    | '/liveokt/$id/steg/$step'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  LiveoktIdRoute: typeof LiveoktIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/liveokt/$id': {
      id: '/liveokt/$id'
      path: '/liveokt/$id'
      fullPath: '/liveokt/$id'
      preLoaderRoute: typeof LiveoktIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/velg-pastander': {
      id: '/_dashboard/velg-pastander'
      path: '/velg-pastander'
      fullPath: '/velg-pastander'
      preLoaderRoute: typeof DashboardVelgPastanderRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/min-samling': {
      id: '/_dashboard/min-samling'
      path: '/min-samling'
      fullPath: '/min-samling'
      preLoaderRoute: typeof DashboardMinSamlingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/lagre-fagprat': {
      id: '/_dashboard/lagre-fagprat'
      path: '/lagre-fagprat'
      fullPath: '/lagre-fagprat'
      preLoaderRoute: typeof DashboardLagreFagpratRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/lag-fagprat': {
      id: '/_dashboard/lag-fagprat'
      path: '/lag-fagprat'
      fullPath: '/lag-fagprat'
      preLoaderRoute: typeof DashboardLagFagpratRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_authed/private': {
      id: '/_authed/private'
      path: '/private'
      fullPath: '/private'
      preLoaderRoute: typeof AuthedPrivateRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/fagprat/$id': {
      id: '/_dashboard/fagprat/$id'
      path: '/fagprat/$id'
      fullPath: '/fagprat/$id'
      preLoaderRoute: typeof DashboardFagpratIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/liveokt/$id/steg/$step': {
      id: '/liveokt/$id/steg/$step'
      path: '/steg/$step'
      fullPath: '/liveokt/$id/steg/$step'
      preLoaderRoute: typeof LiveoktIdStegStepRouteImport
      parentRoute: typeof LiveoktIdRoute
    }
    '/_dashboard/fagprat/$id/rediger': {
      id: '/_dashboard/fagprat/$id/rediger'
      path: '/rediger'
      fullPath: '/fagprat/$id/rediger'
      preLoaderRoute: typeof DashboardFagpratIdRedigerRouteImport
      parentRoute: typeof DashboardFagpratIdRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedPrivateRoute: typeof AuthedPrivateRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedPrivateRoute: AuthedPrivateRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface DashboardFagpratIdRouteChildren {
  DashboardFagpratIdRedigerRoute: typeof DashboardFagpratIdRedigerRoute
}

const DashboardFagpratIdRouteChildren: DashboardFagpratIdRouteChildren = {
  DashboardFagpratIdRedigerRoute: DashboardFagpratIdRedigerRoute,
}

const DashboardFagpratIdRouteWithChildren =
  DashboardFagpratIdRoute._addFileChildren(DashboardFagpratIdRouteChildren)

interface DashboardRouteChildren {
  DashboardLagFagpratRoute: typeof DashboardLagFagpratRoute
  DashboardLagreFagpratRoute: typeof DashboardLagreFagpratRoute
  DashboardMinSamlingRoute: typeof DashboardMinSamlingRoute
  DashboardVelgPastanderRoute: typeof DashboardVelgPastanderRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardFagpratIdRoute: typeof DashboardFagpratIdRouteWithChildren
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardLagFagpratRoute: DashboardLagFagpratRoute,
  DashboardLagreFagpratRoute: DashboardLagreFagpratRoute,
  DashboardMinSamlingRoute: DashboardMinSamlingRoute,
  DashboardVelgPastanderRoute: DashboardVelgPastanderRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardFagpratIdRoute: DashboardFagpratIdRouteWithChildren,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface LiveoktIdRouteChildren {
  LiveoktIdStegStepRoute: typeof LiveoktIdStegStepRoute
}

const LiveoktIdRouteChildren: LiveoktIdRouteChildren = {
  LiveoktIdStegStepRoute: LiveoktIdStegStepRoute,
}

const LiveoktIdRouteWithChildren = LiveoktIdRoute._addFileChildren(
  LiveoktIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  LiveoktIdRoute: LiveoktIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
